# Generated by Django 3.1 on 2020-08-25 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=64)),
                ('email_address', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=32)),
                ('description', models.TextField(max_length=240)),
                ('start_date', models.CharField(max_length=24)),
                ('end_date', models.CharField(default='present', max_length=24)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.user')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Some_High_School', 'Some High School'), ('Diploma_GED', 'High School Diploma / GED'), ('Some_College', 'Some College'), ('Associates', 'Associates Degree'), ('Bachelors', "Bachelor's Degree"), ('Higher', "Master's Degree or Higher")], max_length=16)),
                ('school_name', models.CharField(max_length=64)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.user')),
            ],
        ),
    ]
